### ISSUE TITLE
No credentials found error

### ISSUE THREAD

**Issue by mpas97** [purejava/keepassxc-cryptomator#2]
After installing and activating KeePassXC in Cryptomator settings, I was asked to name the KeePassXC connection. Everything fine so far.

But now when I create a vault or want to open one, I only see those errors. Do I have to manually create entries in KeePassXC or is this a bug?
```
13:05:03.708 [App Background Thread 004] INFO  o.c.u.a.CreateNewVaultPasswordController - Created vault at /Users/test/xxxx
13:05:03.724 [JavaFX Application Thread] INFO  org.purejava.KeepassProxyAccess - org.purejava.KeepassProxyAccessException: ErrorCode: 15, No credentials found
13:05:03.724 [JavaFX Application Thread] INFO  o.p.i.keychain.KeePassXCAccess - No password found for vault X-k5I9Smym5B
```

**Comment by purejava** [comment]
> After installing and activating KeePassXC in Cryptomator settings, I was asked to name the KeePassXC connection. Everything fine so far.
> 
> But now when I create a vault or want to open one, I only see those errors. Do I have to manually create entries in KeePassXC or is this a bug?
> 
> ```
> 13:05:03.708 [App Background Thread 004] INFO  o.c.u.a.CreateNewVaultPasswordController - Created vault at /Users/test/xxxx
> 13:05:03.724 [JavaFX Application Thread] INFO  org.purejava.KeepassProxyAccess - org.purejava.KeepassProxyAccessException: ErrorCode: 15, No credentials found
> 13:05:03.724 [JavaFX Application Thread] INFO  o.p.i.keychain.KeePassXCAccess - No password found for vault X-k5I9Smym5B
> ```

These log messages appear every time in the log file, when an new vault got created. As soon as the vault got added to the list of vaults, Cryptomator tries to load the according password from KeePassXC, which does not exist and therefore can not be found.
Cryptomator does not do that with another password back end configured, e.g. the Mac System Keychain. So I consider this to be a minor bug that should be fixed in Cryptomator. I'll open an according issue there.

You do not need to create entries manually in KeePassXC, Cryptomator does this for you. As soon as you unlock a vault and enter the password for that vault, when you checked the "Remember password" checkbox, the password gets saved in the password back end that was choosen in the Cryptomator preferences before.

And a log message is written, when the password got stored in the password back end. Failures of storing the password in the password back end are logged as well.
